---
# tasks file for mongodb

- name: Include distribution specific variables
  include_vars: "Ubuntu.yml"
  tags: mongodb

- include: Ubuntu.yml
  tags: mongodb

- name: Create MongoDB configuration file
  template: >
    src=mongod.conf.j2
    dest=/etc/mongod.conf
    owner=root
    group=root
    mode=0644
  notify: restart mongodb
  tags: mongodb

- name: Ensure MongoDB service is started and enabled on boot
  service: name={{ mongodb_service_name }} state=started enabled=yes
  tags: mongodb
